CREATE TABLE dbo.Game (
    Id         INT          IDENTITY (1, 1) NOT NULL,
    Player1    VARCHAR (64) NULL,
    Player2    VARCHAR (64) NULL,
    Player3    VARCHAR (64) NULL,
    Player4    VARCHAR (64) NULL,
    Character1 INT NULL,
    Character2 INT NULL,
    Character3 INT NULL,
    Character4 INT NULL,
    Player1Id INT NULL,
    Player2Id INT NULL,
    Player3Id INT NULL,
    Player4Id INT NULL,
    Winner VARCHAR(4) NULL,
    Stage INT NOT NULL,
    GameMode INT NULL,
    StartAt DATETIME NOT NULL,
    GameLength INT NOT NULL,
    FileName VARCHAR(32) NULL,
    Hash VARCHAR(32) NOT NULL,
    Platform VARCHAR(32) NOT NULL,
    Created    DATETIME     NOT NULL,
    Updated    DATETIME     NULL,
    Deleted    DATETIME     NULL,
    PRIMARY KEY CLUSTERED (Id ASC)
);